---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    # - name: Updating packages
    #   yum:
    #     name: '*'
    #    state: 'latest'
    - name: Mongo yum config
      copy:
        dest: '/etc/yum.repos.d/mongodb-org-3.0.repo'
        content: |
          [mongodb-org-3.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.0/x86_64/
          gpgcheck=0
          enabled=1
    - name: Install mongo
      yum:
        name:
          - mongodb-org-3.0.6
          - mongodb-org-server-3.0.6
          - mongodb-org-shell-3.0.6
          - mongodb-org-mongos-3.0.6
          - mongodb-org-tools-3.0.6
        state: present
    - name: Copy mongo config file
      ansible.builtin.copy:
        src: ./config/prod/mongod.conf
        dest: /etc/mongod.conf
        owner: root
        group: root
        mode: '0644'
    - name: New relic infra yum config
      get_url:
        url: https://download.newrelic.com/infrastructure_agent/linux/yum/amazonlinux/2/x86_64/newrelic-infra.repo
        dest: /etc/yum.repos.d/newrelic-infra.repo
    - name: Install new relic
      yum:
        name: newrelic-infra
        state: latest
    - name: Copy new relic config
      ansible.builtin.copy:
        src: ./config/prod/newrelic-infra.yml
        dest: /etc/newrelic-infra.yml
        owner: root
        group: root
        mode: '0644'
