---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    - name: Updating packages
      yum:
        name: '*'
        state: 'latest'
    - name: Mongo yum config
      copy:
        dest: '/etc/yum.repos.d/mongodb-org-3.0.repo'
        content: |
          [mongodb-org-3.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.0/x86_64/
          gpgcheck=0
          enabled=1
    - name: Install mongo
      yum:
        name: mongodb-org
        state: latest
